### ISSUE TITLE
#2 Pr.1: La funcion siguiente es incorrecta

### ISSUE THREAD

**Issue by LorenzoFerraces** [leandro-cuevas/EstrD2023s1#2]
https://github.com/leandro-cuevas/EstrD2023s1/blob/f4e89fc77a26d3b1768e359993dea83a0f5ed081/Practica%201.hs#L54-L58

En tu código consideras los casos de Norte, Sur y Este pero en caso de que te pasen Oeste como argumento, tu función respondería con un error diciendo que lo que le mandaste no era una Dirección

**Comment by leandro-cuevas** [comment]
@LorenzoFerraces Claro, lo interpreté de esa manera en base al enunciado:

"Dada una dirección devuelve su siguiente, en sentido horario, y suponiendo que no existe la siguiente dirección a Oeste.  ¿Posee una precondición esta función? ¿Es una función total o parcial?"

Cuando dice que hay que suponer que no existe el siguiente a Oeste, consideré que debería responder error.

**Comment by LorenzoFerraces** [comment]
Está bien que consideres que tiene que devolver un error porque es así, el problema es el mensaje que le estás devolviendo. Oeste ES una dirección pero si haces "siguiente Oeste" te va a devolver un error diciendo que no le diste una dirección, y no es muy feliz eso

**Comment by leandro-cuevas** [comment]
Resuelto

**Comment by LorenzoFerraces** [comment]
Esta mejor el mensaje de error, pero ahora si yo le pido siguiente de Fidel, me va a responder que Oeste no es una direccion valida, aveces es mejor no complicarse con los mensajes de error y dejar que haskell lo maneje

**Comment by LorenzoFerraces** [comment]
Me encanto el nuevo mensaje de error
