### ISSUE TITLE
#9 Pr.1: La función juntarPokemon no es eficaz, porque tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by LorenzoFerraces** [leandro-cuevas/EstrD2023s1#9]
https://github.com/leandro-cuevas/EstrD2023s1/blob/f4e89fc77a26d3b1768e359993dea83a0f5ed081/Practica%201.hs#L175-L179

Sería bueno tener una subtarea que dado un único entrenador diera la lista de sus Pokemon, y usarla 2 veces. Ya tenes esa funcion definida arriba de juntarPokemon, solo tenes que aprovecharla

**Comment by leandro-cuevas** [comment]
En este caso pensé que un código más corto era mejor, lo modifiqué siguiendo tus indicaciones. Gracias

**Comment by LorenzoFerraces** [comment]
Esta bueno el uso de subtarea, pero fijate que podes pasarle el entrenador entero y no tenes la necesidad de hacer PM en juntarPokemon, lo considero como resuelto pero fijate en esos detalles de no hacer cosas donde no las necesitas
